server:
  port: 8282

spring:
  datasource:
    url: jdbc:sqlserver://192.168.100.5;databaseName=performance_appraisal;encrypt=true;trustServerCertificate=true
    username: sa
    password: Sql@2019
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate:
          dialect: org.hibernate.dialect.SQLServer2012Dialect
          format_sql: true
          show_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


  mail:
    host: smtp.gmail.com
    port: 587
    username: udaydasari2003@gmail.com
    password: tvet ttix vzwn zdzv
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
custom:
  apiKey: 2566e68e32de951520875cd5106d217e93f753ffa04c0ab12e10d2f1c07e22c0
  frontendUrl: "http://localhost:3000"

