server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.100.7:3306/performancemanagement?useSSL=false&serverTimezone=UTC
    username: sagarsoft
    password: Mysql@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
#      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          format_sql: true
          show_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: udaydasari2003@gmail.com
    password: tvet ttix vzwn zdzv
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

custom:
  apiKey: 2566e68e32de951520875cd5106d217e93f753ffa04c0ab12e10d2f1c07e22c0
#  frontendUrl: "http://14.140.148.227:3100"
  frontendUrl: "http://localhost:3000"
#  frontendUrl: "http://rms.sagarsoft.in"
